# Site settings
title: "AI4Astro"
email: anna.scaife@manchester.ac.uk
description: "Lectures & Tutorials on AI for Astronomy"
baseurl: ""
url: "http://ai4astro.github.io"
twitter_username: radastrat
github_username:  as595

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

